/* ============================================================
   My motors Supplies — edita aquí: nombre, WhatsApp, productos, precios.
   Todo lo que ve el cliente sale de este archivo.
   ============================================================ */

const CONFIG = {
  storeName: "My motors Supplies",    // ← nombre del negocio
  whatsapp: "584128206458",         // ← tu número WhatsApp (código país + número, sin +)
  location: "Venezuela",            // ← ciudad / zona
  hours: "Lun–Sáb · 8am–6pm",       // ← horario
  currency: "$",                   // USD
};

const CATEGORIES = ["Todos", "Motor", "Transmisión", "Frenos", "Eléctrico", "Suspensión", "Cauchos", "Accesorios"];

const PRODUCTS = [
  {
    id: "bujia",
    name: "Bujía NGK CR8E",
    category: "Eléctrico",
    price: 4.50,
    img: "img/bujia.jpg",
    badge: "",
    desc: "Encendido confiable y duradero. Compatible con la mayoría de motos 125–200cc.",
  },
  {
    id: "pastillas",
    name: "Pastillas de freno delanteras",
    category: "Frenos",
    price: 8.90,
    img: "img/pastillas.jpg",
    badge: "",
    desc: "Compuesto semi-metálico de frenado firme y bajo desgaste del disco.",
  },
  {
    id: "disco-freno",
    name: "Disco de freno delantero",
    category: "Frenos",
    price: 24.90,
    img: "img/disco-freno.jpg",
    badge: "",
    desc: "Disco perforado en acero inoxidable. Mejora la disipación de calor.",
  },
  {
    id: "cadena",
    name: "Cadena 428H reforzada",
    category: "Transmisión",
    price: 18.50,
    img: "img/cadena.jpg",
    badge: "",
    desc: "Cadena reforzada de 132 eslabones con seguro. Para trabajo diario.",
  },
  {
    id: "kit-arrastre",
    name: "Kit de arrastre completo",
    category: "Transmisión",
    price: 39.90,
    img: "img/kit-arrastre.jpg",
    badge: "Más vendido",
    desc: "Piñón, corona y cadena en un solo kit. La forma más económica de renovar la transmisión.",
  },
  {
    id: "filtro-aceite",
    name: "Filtro de aceite",
    category: "Motor",
    price: 5.50,
    img: "img/filtro-aceite.jpg",
    badge: "",
    desc: "Protege el motor atrapando impurezas. Cámbialo en cada cambio de aceite.",
  },
  {
    id: "filtro-aire",
    name: "Filtro de aire",
    category: "Motor",
    price: 9.90,
    img: "img/filtro-aire.jpg",
    badge: "",
    desc: "Elemento filtrante de alto flujo. Mejora la respuesta del acelerador.",
  },
  {
    id: "amortiguador",
    name: "Amortiguador trasero",
    category: "Suspensión",
    price: 45.00,
    img: "img/amortiguador.jpg",
    badge: "",
    desc: "Amortiguador a gas con precarga ajustable. Recupera la estabilidad de tu moto.",
  },
  {
    id: "caucho-delantero",
    name: "Caucho delantero 90/90-18",
    category: "Cauchos",
    price: 42.00,
    img: "img/caucho-delantero.jpg",
    badge: "",
    desc: "Agarre firme en seco y mojado. Medida estándar para motos de calle.",
  },
  {
    id: "caucho-trasero",
    name: "Caucho trasero 130/70-17",
    category: "Cauchos",
    price: 55.00,
    img: "img/caucho-trasero.jpg",
    badge: "",
    desc: "Compuesto de larga duración para el uso diario. Tracción segura en curva.",
  },
  {
    id: "bateria-12v",
    name: "Batería 12V 7Ah sellada",
    category: "Eléctrico",
    price: 32.00,
    img: "img/bateria-12v.jpg",
    badge: "",
    desc: "Libre de mantenimiento. Arranque fuerte incluso en las mañanas frías.",
  },
  {
    id: "cdi",
    name: "CDI electrónico",
    category: "Eléctrico",
    price: 14.90,
    img: "img/cdi.jpg",
    badge: "",
    desc: "Módulo de encendido de repuesto. Recupera la chispa de tu moto.",
  },
  {
    id: "carburador",
    name: "Carburador PZ27",
    category: "Motor",
    price: 28.50,
    img: "img/carburador.jpg",
    badge: "",
    desc: "Mezcla precisa y ralentí estable. Para motores 125–200cc.",
  },
  {
    id: "espejos",
    name: "Espejos retrovisores (par)",
    category: "Accesorios",
    price: 11.90,
    img: "img/espejos.jpg",
    badge: "",
    desc: "Visión amplia y ajuste firme. Rosca estándar universal.",
  },
  {
    id: "faro-led",
    name: "Faro delantero LED",
    category: "Eléctrico",
    price: 22.90,
    img: "img/faro-led.jpg",
    badge: "Nuevo",
    desc: "Iluminación blanca intensa con bajo consumo. Instalación directa.",
  },
  {
    id: "bandas-traseras",
    name: "Bandas de freno traseras",
    category: "Frenos",
    price: 7.90,
    img: "img/bandas-traseras.jpg",
    badge: "",
    desc: "Para freno de tambor trasero. Frenado parejo y sin chillidos.",
  },
  {
    id: "aceite-4t",
    name: "Aceite 4T 20W-50 (litro)",
    category: "Motor",
    price: 9.50,
    img: "img/aceite-4t.jpg",
    badge: "",
    desc: "Protección total para el motor en el clima venezolano. Cambio cada 2.000 km.",
  },
  {
    id: "casco",
    name: "Casco abatible",
    category: "Accesorios",
    price: 49.90,
    img: "img/casco.jpg",
    badge: "",
    desc: "Mentón abatible, visor transparente y ventilación. Rueda protegido.",
  },
  {
    id: "guantes",
    name: "Guantes de moto",
    category: "Accesorios",
    price: 14.90,
    img: "img/guantes.jpg",
    badge: "",
    desc: "Protección en nudillos y agarre antideslizante. Tallas M a XL.",
  },
  {
    id: "parrilla",
    name: "Parrilla trasera",
    category: "Accesorios",
    price: 19.90,
    img: "img/parrilla.jpg",
    badge: "",
    desc: "Acero reforzado para carga o maletero. Instalación con tornillería incluida.",
  },
];
